### ISSUE TITLE
Deploy Process Mapper to Unity-Dev shared services account

### ISSUE THREAD

**Issue by jjacob7734** [unity-sds/unity-analytics-dapa#14]
Deploy Process Mapper to the `Unity-Dev` shared services account. Previously this was done manually, but this work is to do this with a fully automated Terraform deployment.

Acceptance Criteria:

- [x] Process Mapper deployed to `Unity-Dev` shared service account
- [x] Terraform automation of EC2 instance provisioning
- [x] Terraform automation of backend server (process mapper container) deployment
- [x] Terraform automation of load balancer, listener, and target group
- [x] Terraform automation of DAPA API routes installed in `Unity-Dev` API Gateway
- [x] Terraform automation of VPC Link linkage from API Gateway to load balancer
- [x] Terraform automation of tagging of resources
- [ ] Test API with calls to SDAP time series

**Comment by mike-gangl** [comment]
@jjacob7734 and @zx128 do we have any updates on this ticket? i'm worried we're not on track for the test/prod deployments without significant progress here.

**Comment by GodwinShen** [comment]
@jjacob7734 ping again, I second @mike-gangl concern on the progress of this work.

**Comment by GodwinShen** [comment]
From slack chat with @jjacob7734:

#14 is to deploy Process Mapper to Unity-Dev.  That is deployed, but Zhangfan was blocked on getting the DAPA API automatically installed in the API Gateway

We worked on it together and found a workaround to use v1 of the API instead of v2.  Not ideal, but I suggested he proceed with that so we can get that wrapped up

Before that the automatic provisioning and container deployment was working (and I used it for a couple demos myself to show SDAP time series.  I wanted the DAPA API to be installed automatically before closing that ticket though.

**Comment by jjacob7734** [comment]
I just updated the checklist above.  The only remaining item to get full automation of the process mapper deployment is in the VPC Link (part of the API Gateway configuration that links to the load balancer in private network).

**Comment by zx128** [comment]
Terraforming API-gateway DAPA collections route was blocked by permission issue due to insufficient privilege of developer role. The restriction has been loosened last week and we can add API-gateway resources as "developer" now. Automating API-gateway resources are done except vpclink as Joe noted earlier. Terraform scripts for both DAPA service instance and load balancer have been tested in "unity-test".

**Comment by GodwinShen** [comment]
@zx128, @jjacob7734 can we get a quick update on this ticket?  I've seen a lot of chatter on the slack channel about this one but can't tell how close we are to being done.  what is left to do here?

**Comment by jjacob7734** [comment]
> [@zx128](https://github.com/zx128), [@jjacob7734](https://github.com/jjacob7734) can we get a quick update on this ticket? I've seen a lot of chatter on the slack channel about this one but can't tell how close we are to being done. what is left to do here?

The remaining item is to add configuration of the VPC Link to connect the API in API Gateway to the Load Balancer.  I believe the most recent chatter on Slack is related to a new problem that cropped up where Zhangfan's process mapper instance was terminated (by MCP maybe?) because the AMI needed to be updated (to which AMI?).

**Comment by jjacob7734** [comment]
- VPC Link automation completed.
- Also added another checkpoint item in the ticket's acceptance criteria related to adding the mandatory Unity tags to all resource.  That is also fully automated as part of the Terraform.
- Remaining item is to test it with SDAP time series DAPA calls, but there is an issue related to Cognito authentication that is being worked out with Ramesh.

**Comment by mike-gangl** [comment]
@jjacob7734 in which environments has this been deployed? We'll need it in dev, test, and prod shared service venues.

**Comment by zx128** [comment]
Terraform deployment has been tried in all 3. Env dev and test are straight forward with only changes for vpc, subnets. Env prod has an issue with this deployment error:

aws_instance.unity_dapa_instance: Creating...

Error: creating EC2 Instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=7btbv7tkj4yxnrzltyygo1ipn

How should we resolve this? Has Unity done this as a group?

**Comment by jjacob7734** [comment]
**Status Update**

- Fully automated except for working on an issue with the VPC Link configuration in API Gateway (VPC Link connects to the network load balancer)

**Comment by GodwinShen** [comment]
@jjacob7734 can we get a status update on this ticket?  How are we doing on the VPC link configuration?

**Comment by jjacob7734** [comment]
Completed automated deployment including: 

- EC2 instance provisioning, 
- backend service deployment on EC2, 
- Network Load Balancer, 
- API Gateway DAPA path for process mapper (includes VPC Link and API installation)

This deployment relies on a previously containerized backend service with image published to AWS ECR.

We also rely on Unity Common Services for these items:

- Subnet creation
- API Gateway prefix (under which we deploy `processes`)

Terraform scripts for this deployment are in https://github.com/unity-sds/unity-analytics-dapa/tree/devel/terraform

To deploy we go to that `terraform` directory, prepare the inputs in `terraform.tfvars`, and do the usual:

- terraform init
- terraform plan
- terraform apply
- (terraform destroy)
